flour = int(input("Enter the amount of flour in grams: "))
sugar = int(input("Enter the amount of sugar in grams: "))  
butter = int(input("Enter the amount of butter in grams: "))
eggs = int(input("Enter the number of eggs: "))
chocolatechips = int(input("Enter the amount of chocolate chips in grams: "))
Vanilla_essence = int(input("Enter the amount of vanilla essence in ml: "))
newflour = int(input(flour*6) )
newsugar = int(input(sugar*6) )
newbutter=int(input(butter*6) )
neweggs=int(input(eggs*6) )
newchocolatechips=int(input(chocolatechips*6) )
newvanillaessences=int(input(Vanilla_essence*6) )
print("the amount of flour needed is: "+str(newflour))
print("the amount of sugar needed is: "+str(newsugar))
print("the amount of butter needed is: "+str(newbutter))
print("the number of eggs needed is: "+str(neweggs))
print("the amount of chocolate chips needed is: "+str(newchocolatechips))   
print("the amount of vanilla essence needed is: "+str(newvanillaessences))