Eggs = input("How many eggs have you bought? ")
Milk = input("How many litres of milk have you bought? ")
Bread = input("How many loaves of bread have you bought? ")
EggsPrice = input("What is the price of a dozen eggs? ")
MilkPrice = input("What is the price of a litre of milk? ")
BreadPrice = input("What is the price of a loaf of bread? ")
Quantity = float(Eggs) + float(Milk) + float(Bread)
Total = (float(Eggs) / 12 * float(EggsPrice)) + (float(Milk) * float(MilkPrice)) + (float(Bread) * float(BreadPrice))
print("The total cost is: £" + str(Total))