print("Second Half Action")
print()
input("Enter the home team HT score")
input("Enter the away team HT score")
print()
input("Enter the home team FT score")
input("Enter the away team FT score")
print()
print("The total amount of goals scored after half time is")